version: "3.3"

services:
# ====================================================================================

  grafana-server:
    image: grafana/grafana:5.1.2
    # See https://hub.docker.com/r/grafana/grafana/ for information
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource,camptocamp-prometheus-alertmanager-datasource,grafana-kubernetes-app,grafana-piechart-panel,vonage-status-panel,savantly-heatmap-panel,neocat-cal-heatmap-panel,jdbranham-diagram-panel,natel-plotly-panel,mtanda-histogram-panel,btplc-status-dot-panel,grafana-clock-panel
      - GF_METRICS_ENABLED=true
    ports:
      - "10.0.2.15:80:3000"
    volumes:
      - ../../data/grafana/lib:/var/lib/grafana:rw
      - ../../conf/grafana/etc:/etc/grafana:rw
      - ../../data/grafana/log:/var/log/grafana:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      options:
        max-size: 50m
